/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expert.finder.gui;

/**
 *
 * @author adri
 */
public class GestioConsulta extends javax.swing.JFrame {
    private final ControladorPresentacio controladorPresentacio;
    /**
     * Creates new form MenuConsulta
     */
    public GestioConsulta(ControladorPresentacio controladorPresentacio) {
        initComponents();
        this.controladorPresentacio = controladorPresentacio;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonNuevaConsulta = new javax.swing.JButton();
        BotonModificarConsulta = new javax.swing.JButton();
        BotonEliminarConsulta = new javax.swing.JButton();
        BotonConsultarConsultas = new javax.swing.JButton();
        BotonEnrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonNuevaConsulta.setText("Nova Consulta");
        BotonNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevaConsultaActionPerformed(evt);
            }
        });

        BotonModificarConsulta.setText("Modificar Consulta");
        BotonModificarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarConsultaActionPerformed(evt);
            }
        });

        BotonEliminarConsulta.setText("Eliminar Consulta");
        BotonEliminarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarConsultaActionPerformed(evt);
            }
        });

        BotonConsultarConsultas.setText("Consultar Consultas");
        BotonConsultarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarConsultasActionPerformed(evt);
            }
        });

        BotonEnrere.setText("Enrere");
        BotonEnrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonNuevaConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonModificarConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEliminarConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonConsultarConsultas))
                    .addComponent(BotonEnrere))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevaConsulta)
                    .addComponent(BotonModificarConsulta)
                    .addComponent(BotonEliminarConsulta)
                    .addComponent(BotonConsultarConsultas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(BotonEnrere)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConsultarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarConsultasActionPerformed
        // TODO add your handling code here:
        new ConsultarConsulta(this.controladorPresentacio).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonConsultarConsultasActionPerformed

    private void BotonEnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnrereActionPerformed
        // TODO add your handling code here:
        new Menu(this.controladorPresentacio).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonEnrereActionPerformed

    private void BotonModificarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarConsultaActionPerformed
        // TODO add your handling code here:
        /*
        new ModificarConsulta(controladorpresentacio).setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_BotonModificarConsultaActionPerformed

    private void BotonNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevaConsultaActionPerformed
        // TODO add your handling code here:
        new AfegirConsulta(this.controladorPresentacio).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonNuevaConsultaActionPerformed

    private void BotonEliminarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarConsultaActionPerformed
        // TODO add your handling code here:
        new EliminarConsulta(this.controladorPresentacio).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonEliminarConsultaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultarConsultas;
    private javax.swing.JButton BotonEliminarConsulta;
    private javax.swing.JButton BotonEnrere;
    private javax.swing.JButton BotonModificarConsulta;
    private javax.swing.JButton BotonNuevaConsulta;
    // End of variables declaration//GEN-END:variables
}
