/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expert.finder.gui;

/**
 *
 * @author Admin
 */
public class GestionGraf extends javax.swing.JFrame {
    private final ControladorPresentacio controladorPresentacio;

    /**
     * Creates new form GestionGraf
     */
      public GestionGraf(ControladorPresentacio controladorPresentacio) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controladorPresentacio = controladorPresentacio;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bEnrere = new javax.swing.JButton();
        AfegirNodeButton = new javax.swing.JButton();
        AfegirRelacioButton = new javax.swing.JButton();
        EliminarRelacioButton = new javax.swing.JButton();
        bConsultarNode = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GESTIÓ GRAF");

        bEnrere.setText("Enrere");
        bEnrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnrereActionPerformed(evt);
            }
        });

        AfegirNodeButton.setText("Afegir node");
        AfegirNodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfegirNodeButtonActionPerformed(evt);
            }
        });

        AfegirRelacioButton.setText("Afegir relació");
        AfegirRelacioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfegirRelacioButtonActionPerformed(evt);
            }
        });

        EliminarRelacioButton.setText("Consultar relació");
        EliminarRelacioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarRelacioButtonActionPerformed(evt);
            }
        });

        bConsultarNode.setText("Consultar Node");
        bConsultarNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarNodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AfegirNodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bConsultarNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AfegirRelacioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliminarRelacioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel1))
                            .addComponent(bEnrere))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConsultarNode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AfegirNodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AfegirRelacioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarRelacioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bEnrere)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnrereActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(this.controladorPresentacio);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bEnrereActionPerformed

    private void AfegirNodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfegirNodeButtonActionPerformed
        AfegirNode menu = new AfegirNode(this.controladorPresentacio);        
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AfegirNodeButtonActionPerformed

    private void AfegirRelacioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfegirRelacioButtonActionPerformed
        // TODO add your handling code here:
        ConsultarRelacio menu = new ConsultarRelacio(this.controladorPresentacio);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AfegirRelacioButtonActionPerformed

    private void EliminarRelacioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarRelacioButtonActionPerformed
        // TODO add your handling code here:
        EliminarRelacio menu = new EliminarRelacio(this.controladorPresentacio);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarRelacioButtonActionPerformed

    private void bConsultarNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarNodeActionPerformed
        // TODO add your handling code here:
        ConsultarNode consultarNode = new ConsultarNode(this.controladorPresentacio);
        consultarNode.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bConsultarNodeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AfegirNodeButton;
    private javax.swing.JButton AfegirRelacioButton;
    private javax.swing.JButton EliminarRelacioButton;
    private javax.swing.JButton bConsultarNode;
    private javax.swing.JButton bEnrere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
