/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expert.finder.gui;


/**
 *
 * @author NEW
 */
public class GuiGestionConsulta extends javax.swing.JFrame {

    /**
     * Creates new form GuiGestionConsulta
     */
    private final ControladorPresentacio controladorPresentacio;
    
    
    public GuiGestionConsulta(ControladorPresentacio controladorPresentacio) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controladorPresentacio = controladorPresentacio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevaConsulta = new javax.swing.JButton();
        ConsultarResultados = new javax.swing.JButton();
        EliminarResultados = new javax.swing.JButton();
        tornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NuevaConsulta.setText("Nueva Consulta");
        NuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaConsultaActionPerformed(evt);
            }
        });

        ConsultarResultados.setText("Consultar Resultados");
        ConsultarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarResultadosActionPerformed(evt);
            }
        });

        EliminarResultados.setText("Eliminar Resultados");
        EliminarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarResultadosActionPerformed(evt);
            }
        });

        tornar.setText("Tornar");
        tornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EliminarResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsultarResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(NuevaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tornar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(NuevaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ConsultarResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(EliminarResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(tornar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaConsultaActionPerformed
        // TODO add your handling code here:
        NuevaConsulta menu = new NuevaConsulta(this.controladorPresentacio);        
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NuevaConsultaActionPerformed

    private void ConsultarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarResultadosActionPerformed
        // TODO add your handling code here:
        ConsultarResultados menu = new ConsultarResultados(this.controladorPresentacio);        
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConsultarResultadosActionPerformed

    private void EliminarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarResultadosActionPerformed
        // TODO add your handling code here:
        EliminarResultado menu = new EliminarResultado(this.controladorPresentacio);        
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarResultadosActionPerformed

    private void tornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornarActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(this.controladorPresentacio);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tornarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarResultados;
    private javax.swing.JButton EliminarResultados;
    private javax.swing.JButton NuevaConsulta;
    private javax.swing.JButton tornar;
    // End of variables declaration//GEN-END:variables
}
