/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expert.finder.gui;


import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NEW
 */
public class ModificarResultat extends javax.swing.JFrame {

    private final ControladorPresentacio controladorPresentacio;
    private int numeroConsulta;
    private ArrayList<String> modificacio;
    String column_names[]= {"Nom Node","Grau Rellevancia"};
    private DefaultTableModel table_model=new DefaultTableModel(column_names, 0);
    private String tipusNode = null;
    
    
    /**
     * Creates new form ModificarResultat
     */
    public ModificarResultat(ControladorPresentacio controladorPresentacio, int numeroConsulta) {
        
        this.numeroConsulta = numeroConsulta;
        initComponents();
        this.setLocationRelativeTo(null);
        this.controladorPresentacio = controladorPresentacio;
        this.modificacio = this.controladorPresentacio.get_resultat(numeroConsulta);
        inicializar_taula_resultat();
        
        ArrayList<String> consultes = this.controladorPresentacio.get_consultes();
        String consulta = consultes.get(this.numeroConsulta);
        int primeraBarra = consulta.indexOf('|');
        int segonaBarra = consulta.indexOf("|", primeraBarra+1);
        int terceraBarra = consulta.indexOf("|", segonaBarra+1);
        int cuartaBarra = consulta.indexOf("|", terceraBarra+1);
        String cami = consulta.substring(terceraBarra+1, cuartaBarra);
        
            if (cami.charAt(0) == 'P') tipusNode = "Paper";
            else if (cami.charAt(0) == 'T') tipusNode = "Terme";
            else if (cami.charAt(0) == 'C') tipusNode = "Conferencia";            
            else tipusNode = "Autor";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableResultat = new javax.swing.JTable();
        guardar = new javax.swing.JButton();
        tornar = new javax.swing.JButton();
        modificaCasella = new javax.swing.JButton();
        novaCasella = new javax.swing.JTextField();
        afegirFila = new javax.swing.JButton();
        eliminarFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modificar Resultat");

        TableResultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Node", "Grau Rellevancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableResultat);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        tornar.setText("Tornar");
        tornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornarActionPerformed(evt);
            }
        });

        modificaCasella.setText("Modifica Casella");
        modificaCasella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaCasellaActionPerformed(evt);
            }
        });

        novaCasella.setToolTipText("");
        novaCasella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaCasellaActionPerformed(evt);
            }
        });

        afegirFila.setText("Afegir Fila");
        afegirFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirFilaActionPerformed(evt);
            }
        });

        eliminarFila.setText("Eliminar Fila");
        eliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(guardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tornar)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eliminarFila)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(afegirFila)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(novaCasella, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(modificaCasella)
                                        .addGap(39, 39, 39))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificaCasella)
                    .addComponent(novaCasella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afegirFila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarFila)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tornar)
                    .addComponent(guardar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornarActionPerformed
        // TODO add your handling code here:
        GuiResultat menu = new GuiResultat(this.controladorPresentacio, numeroConsulta, false);
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_tornarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:

        this.controladorPresentacio.afegir_resultat_modificat(this.modificacio,numeroConsulta);
        GuiResultat menu = new GuiResultat(this.controladorPresentacio, numeroConsulta, false);
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_guardarActionPerformed

    private void modificaCasellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaCasellaActionPerformed
        // TODO add your handling code here:
        if(TableResultat.getSelectedRow() != -1 && novaCasella.getText() != ""){
            int i = TableResultat.getSelectedRow();
            int j = TableResultat.getSelectedColumn();
            String nou = novaCasella.getText();
            if(j == 1){
                
                double nouGrau = Double.parseDouble(nou);
                if(nouGrau < 0 || nouGrau > 1){
                     JOptionPane.showMessageDialog(this, "El grau de rellevancia introduit no és vàlid, ha de estar entre 0 i 1 ambdós inclosos.");
                }
                else{ 
                    TableResultat.getModel().setValueAt(nou, i, 1);
                    
                    String novaLinea = modificacio.get(i);
                    int primeraBarra = novaLinea.indexOf('|');
                    int segonaBarra = novaLinea.indexOf("|", primeraBarra+1);
                    String linea = i + "|" + novaLinea.substring(primeraBarra + 1, segonaBarra) + 
                    "|" + tipusNode + "|" + nou;
                    
                    this.modificacio.set(i, linea);

                }
            }
            else {
                TableResultat.getModel().setValueAt(nou, i, 0);
                String novaLinea = modificacio.get(i);
                int ultimaBarra = novaLinea.lastIndexOf("|");

                String linea = i + "|" + nou + 
                "|" + tipusNode + "|" + novaLinea.substring(ultimaBarra + 1, novaLinea.length());
                    
                this.modificacio.set(i, linea);                    
            }
            
            
            
            novaCasella.setText("");
        }
        
    }//GEN-LAST:event_modificaCasellaActionPerformed

    private void novaCasellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaCasellaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_novaCasellaActionPerformed

    private void afegirFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirFilaActionPerformed
        // TODO add your handling code here:
        int i = this.modificacio.size();
        String nodei = "x" + Integer.toString(i+1);
        String Gr = "0.000001";
        table_model.addRow(new Object [] {nodei, Gr});
        TableResultat.setModel(table_model);
        
        String linea = i + "|" + nodei + "|" + tipusNode + "|" + Gr;
        this.modificacio.add(linea);
    }//GEN-LAST:event_afegirFilaActionPerformed

    private void eliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFilaActionPerformed
        // TODO add your handling code here:
        int i = TableResultat.getSelectedRow();
        table_model.removeRow(i);
        this.modificacio.remove(i);
    }//GEN-LAST:event_eliminarFilaActionPerformed


    public void inicializar_taula_resultat(){

        for(int j = 0; j < modificacio.size(); ++j){
            String nodeGrau = modificacio.get(j);
            String nomNode = nodeGrau.substring(nodeGrau.indexOf('|')+1, nodeGrau.indexOf("|", nodeGrau.indexOf('|')+1));
            String grau = nodeGrau.substring(nodeGrau.lastIndexOf('|')+1, nodeGrau.length());
            table_model.addRow(new Object [] {nomNode, grau}); 
        }
        
        TableResultat.setModel(table_model);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableResultat;
    private javax.swing.JButton afegirFila;
    private javax.swing.JButton eliminarFila;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificaCasella;
    private javax.swing.JTextField novaCasella;
    private javax.swing.JButton tornar;
    // End of variables declaration//GEN-END:variables
}
